/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type MindItemType = 'note' | 'link' | 'image' | 'quote' | 'color' | 'article' | 'video' | 'recipe' | 'document' | 'music' | 'tweet' | 'voice';

export interface MindItem {
  id: string;
  type: MindItemType;
  title: string;
  content: string; // Used for note text, link description, or quote body
  url?: string; // For links and articles
  imageUrl?: string; // For uploaded images or link preview screenshots
  colorHex?: string; // For color swatches (single color)
  colorPalette?: string[]; // Multiple hex colors for palette cards
  tags: string[]; // Combined tags for searching
  manualTags?: string[]; // Tags added explicitly by the user
  aiTags?: string[]; // Tags generated by Gemini
  createdAt: string; // ISO String
  isArchived?: boolean;
  isFavorite?: boolean;
  isTopMind?: boolean; // Focus-mode pinning
  analyzing?: boolean; // True while Gemini is parsing/scraping in background
  dominantColor?: string; // Close color group (e.g. "blue", "red")
  audioUrl?: string; // Base64 or Blob URL for recorded voice notes
  aiSummary?: string; // 1-sentence AI summary of the item
  bodyText?: string; // Temporary scraped article context
  
  // Extra parsed metadata
  readingTime?: number; // In minutes, for articles
  siteName?: string; // e.g. "Medium", "YouTube", "Spotify"
  author?: string; // For quotes, articles, or tweets
  authorUsername?: string; // For tweets/social posts
  authorAvatar?: string; // For tweets
  favicon?: string; // URL to favicon
  duration?: string; // Video duration or recipe prep time
  ingredients?: string[]; // For recipes
  steps?: string[]; // For recipes
  fileSize?: string; // For PDFs/documents
  pageCount?: number; // For PDFs/documents
}

export interface SerendipityPrompt {
  id: string;
  prompt: string;
  type: 'tag' | 'time' | 'random' | 'color';
  value: string;
}

export type AchievementRarity = 'Common' | 'Rare' | 'Epic' | 'Legendary';

export interface Achievement {
  id: string;
  title: string;
  description: string;
  rarity: AchievementRarity;
  icon?: any; // Icon component reference
  image?: string; // Optional illustration URL
  xp?: number; // Optional experience points/movement value
  unlockedAt?: string; // ISO date string when unlocked
}
