/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type MindItemType = 'note' | 'link' | 'image' | 'quote' | 'color' | 'article' | 'video' | 'recipe' | 'document' | 'music' | 'tweet' | 'voice' | 'film' | 'album' | 'product';

export interface NoteStyle {
  fontFamily?: 'serif' | 'sans' | 'mono' | 'display';
  fontSize?: 'sm' | 'base' | 'lg' | 'xl';
  color?: string; // hex
  bgColor?: string; // hex
  bold?: boolean;
  italic?: boolean;
}

export interface MindItem {
  id: string;
  type: MindItemType;
  title: string;
  content: string; // Used for note text, link description, or quote body
  url?: string; // For links and articles
  imageUrl?: string; // For uploaded images or link preview screenshots
  colorHex?: string; // For color swatches (single color)
  colorPalette?: string[]; // Multiple hex colors for palette cards
  tags: string[]; // Combined tags for searching
  manualTags?: string[]; // Tags added explicitly by the user
  aiTags?: string[]; // Tags generated by Gemini
  createdAt: string; // ISO String
  isArchived?: boolean;
  isFavorite?: boolean;
  readLater?: boolean;
  isTopMind?: boolean; // Focus-mode pinning
  analyzing?: boolean; // True while Gemini is parsing/scraping in background
  dominantColor?: string; // Close color group (e.g. "blue", "red")
  audioUrl?: string; // Base64 or Blob URL for recorded voice notes
  aiSummary?: string; // 1-sentence AI summary of the item
  bodyText?: string; // Temporary scraped article context

  // Status tracking
  isRead?: boolean; // For articles, books
  isWatched?: boolean; // For films, videos
  readAt?: string; // ISO date when marked read
  watchedAt?: string; // ISO date when marked watched

  // Note styling
  noteStyle?: NoteStyle;

  // Extra parsed metadata
  readingTime?: number; // In minutes, for articles
  siteName?: string; // e.g. "Medium", "YouTube", "Spotify"
  author?: string; // For quotes, articles, or tweets
  authorUsername?: string; // For tweets/social posts
  authorAvatar?: string; // For tweets
  favicon?: string; // URL to favicon
  duration?: string; // Video duration or recipe prep time
  ingredients?: string[]; // For recipes
  steps?: string[]; // For recipes
  fileSize?: string; // For PDFs/documents
  pageCount?: number; // For PDFs/documents

  // Film metadata
  moviePoster?: string; // Poster image URL or generated gradient key
  rating?: string; // e.g. "8.3/10" or "PG-13"
  runtime?: string; // e.g. "148 min"
  genre?: string[]; // e.g. ["Sci-Fi", "Thriller"]
  releaseYear?: number;
  director?: string;
  cast?: string[];

  // Album metadata
  albumArtUrl?: string;
  trackCount?: number;
  albumYear?: number;
  albumLabel?: string;

  // Product metadata
  price?: string;
  currency?: string; // e.g. "USD", "EUR"
  brand?: string;
  materials?: string;
  productImageUrl?: string;
  buyUrl?: string;

  // Storage bucket file IDs (for Appwrite media management)
  imageFileId?: string; // File ID in storage bucket for uploaded images
  audioFileId?: string; // File ID in storage bucket for voice recordings
}

export interface SerendipityPrompt {
  id: string;
  prompt: string;
  type: 'tag' | 'time' | 'random' | 'color';
  value: string;
}

export type AchievementRarity = 'Common' | 'Rare' | 'Epic' | 'Legendary';

export interface Achievement {
  id: string;
  title: string;
  description: string;
  rarity: AchievementRarity;
  icon?: any; // Icon component reference
  image?: string; // Optional illustration URL
  xp?: number; // Optional experience points/movement value
  unlockedAt?: string; // ISO date string when unlocked
  quote?: string;
  author?: string;
  lore?: string;
}
